### ISSUE TITLE
INFOGRAFIA

### ISSUE THREAD

**Issue by CxrlosMX** [SistemasTecTlaxiaco/infografia-CxrlosMX-1#1]
[Infografia Ing De Software- Luis Carlos Rendon Aparicio.pdf](https://github.com/SistemasTecTlaxiaco/infografia-CxrlosMX-1/files/8056270/Infografia.Ing.De.Software-.Luis.Carlos.Rendon.Aparicio.pdf)

**Comment by Abraham890** [comment]
Calificación:20 puntos

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
